name: PR CI

on:
  pull_request:
    branches:
      - master

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/Tuist/Dependencies

jobs:
  prepare-ci:
    name: âš™ï¸ prepare for CI
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Compute dependency cache key
        id: compute_hash
        run: echo "hash=${{ hashFiles('Tuist/Dependencies.swift') }}" >> $GITHUB_OUTPUT

      - name: Check dependency cache
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_hash.outputs.hash }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: tuist fetch

  build:
    name: ğŸ¢ Build
    runs-on: macos-latest
    needs: prepare-ci

    steps:
      - uses: actions/checkout@v2

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: tuist fetch

      - name: build tuist
        run: TUIST_CI=1 tuist build

  test:
    name: ğŸ§ª Test
    runs-on: macos-latest
    needs: prepare-ci

    steps:
      - uses: actions/checkout@v2

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: tuist fetch

      - name: test tuist
        run: TUIST_CI=1 tuist test
